"""
Django settings for coffee_core project.

Generated by 'django-admin startproject' using Django 4.2.7.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jlu3ge+f&1)(qvh!(d%gipa%jj72q3aimkgq-dbj!sf#l(e+r8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',          # <--- ПЕРВЫЙ
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',        # <--- Для сокетов
    'coffee',          # <--- Твое приложение
    # 'rest_framework', <--- УДАЛИ ЭТУ СТРОКУ, ОНА ЛОМАЕТ СЕРВЕР
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'coffee_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [], # Если ваши шаблоны в папке coffee/templates, здесь можно оставить пустым
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'coffee_core.wsgi.application'
# Добавляем настройку ASGI приложения
ASGI_APPLICATION = 'coffee_core.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Almaty'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Это скажет Django искать файлы в твоих папках приложений
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Настройка слоев каналов (Channel Layers)
# Используем In-Memory для локальной разработки.
# Для продакшена (Docker/Server) здесь обычно ставят Redis.
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}



# Разрешаем куки без HTTPS (для локальной разработки)
# --- В САМОМ НИЗУ ФАЙЛА ---

# Важно: False для локальной разработки
# --- ВСТАВИТЬ В САМЫЙ КОНЕЦ settings.py ---

# 1. Отключаем требование HTTPS (так как мы на локальном компьютере)
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False

# 2. Разрешаем чтение куки через JavaScript (иногда помогает)
CSRF_COOKIE_HTTPONLY = False

# 3. Говорим Django, что этому адресу можно доверять
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
]
# settings.py

# Указываем, что хотим отправлять через настоящий SMTP сервер Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Ваша почта (ОТ КОГО будет письмо)
EMAIL_HOST_USER = 'saparnursat727@gmail.com'
# ВНИМАНИЕ: Сюда вставляем те 16 букв, которые дал Google (без пробелов)
# НЕ ваш обычный пароль от входа!
EMAIL_HOST_PASSWORD = 'bcuevdtmniandiwq' 

# Почта администратора (куда приходят копии ошибок)
X_FRAME_OPTIONS = 'SAMEORIGIN'