# Generated by Django 6.0.1 on 2026-02-07 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('unit', models.CharField(max_length=10, verbose_name='Ед. измерения (мл/г)')),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Остаток на складе')),
                ('is_milk', models.BooleanField(default=False, verbose_name='Это молоко (для замены)')),
                ('min_limit', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Критический остаток')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Базовая цена')),
                ('category', models.CharField(choices=[('coffee', 'Кофе'), ('dessert', 'Десерты'), ('other', 'Другое'), ('snacks', 'Снеки')], default='coffee', max_length=20, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Компания / Имя')),
                ('contact_info', models.CharField(max_length=100, verbose_name='Telegram/Email для заказа')),
            ],
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Цена')),
                ('quantity_needed', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Расход')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee.ingredient', verbose_name='Списание')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], default='M', max_length=1)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.menuitem')),
                ('modifiers', models.ManyToManyField(blank=True, to='coffee.modifier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='coffee.order')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Расход (M)')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.ingredient')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='coffee.menuitem')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee.supplier', verbose_name='Основной поставщик'),
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата поставки')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Итого по чеку')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.supplier', verbose_name='Поставщик')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за ед.')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Кол-во')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма всего')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.ingredient', verbose_name='Ингредиент')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='coffee.supply')),
            ],
        ),
    ]
