# Generated by Django 4.2.7 on 2026-01-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('coffee', 'Кофе'), ('dessert', 'Десерты'), ('other', 'Другое')], default='coffee', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Цена'),
        ),
    ]
