# Generated by Django 6.0.1 on 2026-02-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='reorder_sent',
            field=models.BooleanField(default=False, verbose_name='Заказ поставщику отправлен'),
        ),
    ]
