# Generated by Django 4.2.7 on 2026-01-20 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_menuitem_category_alter_menuitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('S', 'Small (0.7x)'), ('M', 'Medium (1.0x)'), ('L', 'Large (1.3x)')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('coffee', 'Кофе'), ('dessert', 'Десерты'), ('other', 'Другое')], default='coffee', max_length=20),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Базовая цена (M)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='quantity_needed',
            field=models.FloatField(verbose_name='Количество на порцию (M)'),
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название добавки')),
                ('price', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Цена добавки')),
                ('quantity_needed', models.FloatField(default=0, verbose_name='Расход (мл/г)')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.ingredient', verbose_name='Связанный ингредиент')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='modifiers',
            field=models.ManyToManyField(blank=True, to='coffee.modifier'),
        ),
    ]
