# Generated by Django 4.2.7 on 2026-02-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_ingredient_reorder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifier',
            name='type',
            field=models.CharField(choices=[('syrup', 'Сиропы'), ('milk', 'Молоко'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория'),
        ),
    ]
