# Generated by Django 4.2.7 on 2026-01-20 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_orderitem_size_alter_menuitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifier',
            name='category',
            field=models.CharField(choices=[('syrup', 'Сиропы'), ('milk', 'Молоко / Альтернатива'), ('topping', 'Посыпки / Прочее')], default='syrup', max_length=20, verbose_name='Тип модификатора'),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.ingredient', verbose_name='Что списывать'),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название (на кнопке)'),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Цена'),
        ),
    ]
