# Generated by Django 4.2.7 on 2026-01-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_modifier_category_alter_modifier_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='s_milk',
            field=models.BooleanField(default=False, verbose_name='Это молоко (для замены)'),
        ),
    ]
