# Generated by Django 4.2.7 on 2026-02-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_modifier_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_sized',
            field=models.BooleanField(default=True, verbose_name='Имеет размеры (S/M/L)'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('coffee', 'Кофе'), ('tea', 'Чай'), ('cold', 'Хол. напитки'), ('pastry', 'Выпечка'), ('bowl', 'Боулы'), ('other', 'Другое')], default='coffee', max_length=20, verbose_name='Категория'),
        ),
    ]
