# Generated by Django 4.2.7 on 2026-02-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_menuitem_is_sized_alter_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='has_ice_mods',
            field=models.BooleanField(default=False, verbose_name='Выбор льда'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='has_milk_mods',
            field=models.BooleanField(default=False, verbose_name='Выбор молока'),
        ),
    ]
