# Generated by Django 4.2.7 on 2026-01-20 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_ingredient_s_milk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='s_milk',
            new_name='is_milk',
        ),
    ]
