# Generated by Django 4.2.7 on 2026-02-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_menuitem_has_ice_mods_menuitem_has_milk_mods'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='has_other_mods',
            field=models.BooleanField(default=False, verbose_name='МОЖНО: Прочее (корица и т.д.)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='has_syrup_mods',
            field=models.BooleanField(default=False, verbose_name='МОЖНО: Сиропы'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='has_ice_mods',
            field=models.BooleanField(default=False, verbose_name='МОЖНО: Лёд'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='has_milk_mods',
            field=models.BooleanField(default=False, verbose_name='МОЖНО: Молоко'),
        ),
    ]
