# Generated by Django 4.2.7 on 2026-01-20 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_rename_s_milk_ingredient_is_milk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Компания / Имя')),
                ('contact_info', models.CharField(max_length=100, verbose_name='Telegram/Email для заказа')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата поставки')),
                ('total_cost', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Сумма закупки')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='Фото чека')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.supplier', verbose_name='Поставщик')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='min_limit',
            field=models.FloatField(default=0, verbose_name='Критический остаток (когда заказывать)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='restock_amount',
            field=models.FloatField(default=0, verbose_name='Сколько заказывать (партия)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Остаток'),
        ),
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Пришло (кол-во)')),
                ('cost', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Стоимость этой позиции')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.ingredient', verbose_name='Ингредиент')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='coffee.supply')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee.supplier', verbose_name='Основной поставщик'),
        ),
    ]
