# Generated by Django 4.2.7 on 2026-02-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_menuitem_has_other_mods_menuitem_has_syrup_mods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifier',
            name='type',
            field=models.CharField(choices=[('syrup', 'Сиропы'), ('milk', 'Молоко'), ('other', 'Добавки'), ('ice', 'Лёд')], default='other', max_length=20, verbose_name='Категория'),
        ),
    ]
