# Generated by Django 4.2.7 on 2026-02-11 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0008_alter_modifier_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Открытие')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрытие')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('total_sales', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Выручка')),
                ('order_count', models.IntegerField(default=0, verbose_name='Кол-во заказов')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='coffee.shift'),
        ),
    ]
