# Generated by Django 4.2.7 on 2026-01-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0008_alter_menuitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='supplyitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена за ед.'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='total_cost',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10, verbose_name='Итого по чеку'),
        ),
        migrations.AlterField(
            model_name='supplyitem',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Сумма всего'),
        ),
    ]
