# Generated by Django 4.2.7 on 2026-01-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0009_remove_supplyitem_quantity_supplyitem_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyitem',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Кол-во'),
            preserve_default=False,
        ),
    ]
