# Generated by Django 4.2.7 on 2026-02-11 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0010_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Stock Amount'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='is_milk',
            field=models.BooleanField(default=False, verbose_name='Is Milk (for substitution)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='min_limit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Minimum Limit'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='reorder_sent',
            field=models.BooleanField(default=False, verbose_name='Reorder Sent'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee.supplier', verbose_name='Main Supplier'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(max_length=10, verbose_name='Unit (ml/g)'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('coffee', 'Coffee'), ('tea', 'Tea'), ('cold', 'Cold Drinks'), ('pastry', 'Pastry'), ('bowl', 'Bowls'), ('other', 'Other')], default='coffee', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='has_ice_mods',
            field=models.BooleanField(default=False, verbose_name='Allows: Ice'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='has_milk_mods',
            field=models.BooleanField(default=False, verbose_name='Allows: Milk'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='has_other_mods',
            field=models.BooleanField(default=False, verbose_name='Allows: Other'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='has_syrup_mods',
            field=models.BooleanField(default=False, verbose_name='Allows: Syrups'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_sized',
            field=models.BooleanField(default=True, verbose_name='Has Sizes (S/M/L)'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Base Price'),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee.ingredient', verbose_name='Inventory Deduction'),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='quantity_needed',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantity Needed'),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='type',
            field=models.CharField(choices=[('syrup', 'Syrups'), ('milk', 'Milk'), ('other', 'Additions'), ('ice', 'Ice')], default='other', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Price at Sale'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='quantity_needed',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity Needed (M)'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed at'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='opened_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Opened at'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='order_count',
            field=models.IntegerField(default=0, verbose_name='Order Count'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='total_sales',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Total Sales'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_info',
            field=models.CharField(max_length=100, verbose_name='Contact Info (Telegram/Email)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Company / Name'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Supply Date'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total Cost'),
        ),
        migrations.AlterField(
            model_name='supplyitem',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Item Cost'),
        ),
        migrations.AlterField(
            model_name='supplyitem',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.ingredient', verbose_name='Ingredient'),
        ),
        migrations.AlterField(
            model_name='supplyitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='supplyitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Unit Price'),
        ),
    ]
